platform :ios, '11.0'

source 'https://cdn.cocoapods.org/'

target 'BrazeContentCardsSampleApp' do
  # pod 'Appboy-iOS-SDK/ContentCards', :path => './../../../'
  pod 'Appboy-iOS-SDK/ContentCards'
end
