source 'http://rubygems.org'

gem 'mongo'
gem 'bson'
gem 'bson_ext'
gem 'nokogiri'
gem 'cocoapods'
gem 'multi_json'
gem 'rest-client'
gem 'ocunit2junit'
gem 'match'
gem 'fastlane'
gem 'pbxplorer'
gem 'appboy_sdk_release_utils', :git => 'git@github.com:Appboy/sdk-utils.git'