source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'HelloSwift' do
  platform :ios, '9.0'
  pod 'Appboy-iOS-SDK'
  #pod 'Appboy-iOS-SDK', :path => './../../Appboy-iOS-SDK/'
end

target 'HelloSwiftNotificationContentExtension' do
  platform :ios, '10.0'
  pod 'Appboy-Push-Story', '~>3.0'
  #pod 'Appboy-Push-Story', :path => './../../Appboy-Push-Story/'
end

target 'tvOS_HelloSwift' do
  platform :tvos, '9.0'
  pod 'Appboy-tvOS-SDK'
end
