# We use the spec repository instead of the cdn because it is doesn't suffer
# from the cdn's caching delays.
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'HelloSwift' do
  platform :ios, '11.0'
  pod 'Appboy-iOS-SDK'
  # pod 'Appboy-iOS-SDK', :path => './../../Appboy-iOS-SDK/'

  target 'HelloSwiftTests' do
    inherit! :search_paths
    pod 'OCMock'
  end
  
end

target 'HelloSwiftNotificationContentExtension' do
  platform :ios, '11.0'
  pod 'Appboy-Push-Story'
  # pod 'Appboy-Push-Story', :path => './../../Appboy-Push-Story/'
end

target 'tvOS_HelloSwift' do
  platform :tvos, '11.0'
  pod 'Appboy-tvOS-SDK'
  # pod 'Appboy-tvOS-SDK', :path => './../../Appboy-tvOS-SDK/'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        # Fix bundle targets' 'Signing Certificate' to 'Sign to Run Locally'
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGN_IDENTITY[sdk=macosx*]'] = '-'
            end
        end
    end
end
