blank_issues_enabled: false
contact_links:
  - name: Braze Swift SDK
    url: https://github.com/braze-inc/braze-swift-sdk/
    about: Consider upgrading to the new Braze Swift SDK for a better experience.
  - name: Braze Support
    url: https://support.braze.com/
    about: Contact Braze Support for company or campaign-specific troubleshooting
  - name: Security Issues
    url: https://www.braze.com/docs/developer_guide/disclosures/security_and_vulnerability_disclosure/
    about: Please report security vulnerabilities here.
