blank_issues_enabled: false
contact_links:
  - name: Braze Support
    url: https://support.braze.com/
    about: Contact Braze Support for company or campaign-specific troubleshooting
  - name: Security Issues
    url: https://www.braze.com/docs/developer_guide/disclosures/security_and_vulnerability_disclosure/
    about: Please report security vulnerabilities here.
