name: ✅ Feature Request
description: Request New SDK Features
title: '[Feature]: '
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Did you know: You can also submit feature requests in our [Public Roadmap Portal](https://dashboard.braze.com/resources/roadmap)
  - type: textarea
    id: problem
    attributes:
      label: What problem are you facing?
      description: Help us understand what you're unable to accomplish, or what's difficult with your integration
      placeholder: |
        ex: I am unable to accomplish XYZ today, since the SDK does not allow me to...
    validations:
      required: true
  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds
      description: Are there any workarounds you can use? How complicated are they?
    validations:
      required: true
  - type: textarea
    id: ideal_solution
    attributes:
      label: Ideal Solution
      description: What would your ideal solution look like?
    validations:
      required: false
  - type: textarea
    id: other_information
    attributes:
      label: Other Information
      description: Any additional information you'd like to share?
    validations:
      required: false
