platform :ios, '9.0'

# We use the spec repository instead of the cdn because it is doesn't suffer
# from the cdn's caching delays.
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ObjCSample' do
  pod 'Appboy-iOS-SDK/Core'
end

