platform :ios, '9.0'

# We use the spec repository instead of the cdn because it is doesn't suffer
# from the cdn's caching delays.
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ObjCSample' do
  pod 'Appboy-iOS-SDK/Core'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        # Fix bundle targets' 'Signing Certificate' to 'Sign to Run Locally'
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGN_IDENTITY[sdk=macosx*]'] = '-'
            end
        end
    end
end
