# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.99.0"

lane :matchFullAccess do
  match(
    type: "development", 
    app_identifier: [
      "com.appboy.stopwatch",
      "com.appboy.stopwatch.StopwatchNotificationService",
      "com.appboy.stopwatch.StopwatchNotificationContentExtension"
    ],
    force_for_new_devices: true
  )
  # We don't use `force_for_new_devices: true` for `type: "appstore"` as this
  # option is not supported and generates a warning
  match(
    type: "appstore", 
    app_identifier: [
      "com.appboy.stopwatch",
      "com.appboy.stopwatch.StopwatchNotificationService",
      "com.appboy.stopwatch.StopwatchNotificationContentExtension"
    ]
  )
end

lane :matchReadOnly do
  match(
    type: "development",
    readonly: true,
    app_identifier: [
      "com.appboy.stopwatch",
      "com.appboy.stopwatch.StopwatchNotificationService",
      "com.appboy.stopwatch.StopwatchNotificationContentExtension"
    ],
    force_for_new_devices: true
  )
  # We don't use `force_for_new_devices: true` for `type: "appstore"` as this
  # option is not supported and generates a warning
  match(
    type: "appstore",
    readonly: true,
    app_identifier: [
      "com.appboy.stopwatch",
      "com.appboy.stopwatch.StopwatchNotificationService",
      "com.appboy.stopwatch.StopwatchNotificationContentExtension"
    ]
  )
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
